name: Deployment to GH pages

on: push
branches: [main]

jobs:
  install:
    name: Install dependencies to current machine (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Install go
        run: sudo apt install node -y && npm run deploy