name: Deployment to GH pages

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js Modules
        run: npm install
      - name: Deployment
        run: npm run deploy
