name: Deployment to GH pages

on: push

jobs:
  install:
    name: Install dependencies to current machine (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        run: npm run deploy