name: Deployment to GH pages

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js Modules
        run: npm install
      - name: Setup git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: 'Oleksiy Rudenko'
          email: 'oleksiy.rudenko@domain.com'
          actor: 'OleksiyRudenko'
          token: '${{ secrets.GH_PAT_WEB_CENTRAL }}'
      - name: Deployment
        run: npm run deploy
